// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/miniaudio_ffi.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class MiniaudioFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MiniaudioFfiBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MiniaudioFfiBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Initialize the audio device.
  /// @param sample_rate  Audio sample rate (e.g., 44100, 48000)
  /// @param channels     Number of channels (1 = mono, 2 = stereo)
  /// @param buffer_frames Period size in frames (lower = lower latency)
  /// @return 0 on success, -1 on failure
  int ma_bridge_init(
    int sample_rate,
    int channels,
    int buffer_frames,
  ) {
    return _ma_bridge_init(
      sample_rate,
      channels,
      buffer_frames,
    );
  }

  late final _ma_bridge_initPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int)>>(
          'ma_bridge_init');
  late final _ma_bridge_init =
      _ma_bridge_initPtr.asFunction<int Function(int, int, int)>();

  /// Start audio playback.
  /// @return 0 on success, -1 on failure
  int ma_bridge_start() {
    return _ma_bridge_start();
  }

  late final _ma_bridge_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ma_bridge_start');
  late final _ma_bridge_start =
      _ma_bridge_startPtr.asFunction<int Function()>();

  /// Stop audio playback.
  /// @return 0 on success, -1 on failure
  int ma_bridge_stop() {
    return _ma_bridge_stop();
  }

  late final _ma_bridge_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ma_bridge_stop');
  late final _ma_bridge_stop = _ma_bridge_stopPtr.asFunction<int Function()>();

  /// Get the total number of frames consumed by the audio device.
  /// Used for synchronization calculations in Dart.
  /// @return Total frames consumed since start
  int ma_bridge_get_frames_consumed() {
    return _ma_bridge_get_frames_consumed();
  }

  late final _ma_bridge_get_frames_consumedPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function()>>(
          'ma_bridge_get_frames_consumed');
  late final _ma_bridge_get_frames_consumed =
      _ma_bridge_get_frames_consumedPtr.asFunction<int Function()>();

  /// Get current FIFO fill level in samples.
  /// @return Number of samples available in FIFO
  int ma_bridge_get_fifo_available() {
    return _ma_bridge_get_fifo_available();
  }

  late final _ma_bridge_get_fifo_availablePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
          'ma_bridge_get_fifo_available');
  late final _ma_bridge_get_fifo_available =
      _ma_bridge_get_fifo_availablePtr.asFunction<int Function()>();

  /// Advanced Controls
  void ma_bridge_set_volume(
    double volume,
  ) {
    return _ma_bridge_set_volume(
      volume,
    );
  }

  late final _ma_bridge_set_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'ma_bridge_set_volume');
  late final _ma_bridge_set_volume =
      _ma_bridge_set_volumePtr.asFunction<void Function(double)>();

  int ma_bridge_get_device_sample_rate() {
    return _ma_bridge_get_device_sample_rate();
  }

  late final _ma_bridge_get_device_sample_ratePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
          'ma_bridge_get_device_sample_rate');
  late final _ma_bridge_get_device_sample_rate =
      _ma_bridge_get_device_sample_ratePtr.asFunction<int Function()>();

  int ma_bridge_get_device_channels() {
    return _ma_bridge_get_device_channels();
  }

  late final _ma_bridge_get_device_channelsPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
          'ma_bridge_get_device_channels');
  late final _ma_bridge_get_device_channels =
      _ma_bridge_get_device_channelsPtr.asFunction<int Function()>();

  /// Get device count.
  /// @param type 0 = Playback, 1 = Capture.
  int ma_bridge_context_get_device_count(
    int type,
  ) {
    return _ma_bridge_context_get_device_count(
      type,
    );
  }

  late final _ma_bridge_context_get_device_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32)>>(
          'ma_bridge_context_get_device_count');
  late final _ma_bridge_context_get_device_count =
      _ma_bridge_context_get_device_countPtr.asFunction<int Function(int)>();

  /// Get device info at index.
  /// @param type 0 = Playback, 1 = Capture.
  /// @param index Device index.
  /// @param name_buffer Buffer to store device name (utf8).
  /// @param name_len Size of name buffer.
  /// @param id_buffer Buffer to store device ID (ma_device_id, usually bytes).
  /// @param id_len Size of id buffer (sizeof(ma_device_id)).
  int ma_bridge_context_get_device_info(
    int type,
    int index,
    ffi.Pointer<ffi.Char> name_buffer,
    int name_len,
    ffi.Pointer<ffi.Void> id_buffer,
    int id_len,
  ) {
    return _ma_bridge_context_get_device_info(
      type,
      index,
      name_buffer,
      name_len,
      id_buffer,
      id_len,
    );
  }

  late final _ma_bridge_context_get_device_infoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Int32,
              ffi.Int32,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<ffi.Void>,
              ffi.Int32)>>('ma_bridge_context_get_device_info');
  late final _ma_bridge_context_get_device_info =
      _ma_bridge_context_get_device_infoPtr.asFunction<
          int Function(int, int, ffi.Pointer<ffi.Char>, int,
              ffi.Pointer<ffi.Void>, int)>();

  /// Initialize the audio device with optional device ID.
  /// @param device_id Pointer to ma_device_id (can be NULL for default).
  int ma_bridge_init_with_device_id(
    ffi.Pointer<ffi.Void> device_id,
    int sample_rate,
    int channels,
    int buffer_frames,
  ) {
    return _ma_bridge_init_with_device_id(
      device_id,
      sample_rate,
      channels,
      buffer_frames,
    );
  }

  late final _ma_bridge_init_with_device_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Int, ffi.Int,
              ffi.Int)>>('ma_bridge_init_with_device_id');
  late final _ma_bridge_init_with_device_id = _ma_bridge_init_with_device_idPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, int, int, int)>();

  /// Initialize the high-level audio engine.
  /// @return 0 on success.
  int ma_bridge_engine_init() {
    return _ma_bridge_engine_init();
  }

  late final _ma_bridge_engine_initPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ma_bridge_engine_init');
  late final _ma_bridge_engine_init =
      _ma_bridge_engine_initPtr.asFunction<int Function()>();

  void ma_bridge_engine_uninit() {
    return _ma_bridge_engine_uninit();
  }

  late final _ma_bridge_engine_uninitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'ma_bridge_engine_uninit');
  late final _ma_bridge_engine_uninit =
      _ma_bridge_engine_uninitPtr.asFunction<void Function()>();

  int ma_bridge_engine_start() {
    return _ma_bridge_engine_start();
  }

  late final _ma_bridge_engine_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ma_bridge_engine_start');
  late final _ma_bridge_engine_start =
      _ma_bridge_engine_startPtr.asFunction<int Function()>();

  int ma_bridge_engine_stop() {
    return _ma_bridge_engine_stop();
  }

  late final _ma_bridge_engine_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ma_bridge_engine_stop');
  late final _ma_bridge_engine_stop =
      _ma_bridge_engine_stopPtr.asFunction<int Function()>();

  void ma_bridge_engine_set_volume(
    double volume,
  ) {
    return _ma_bridge_engine_set_volume(
      volume,
    );
  }

  late final _ma_bridge_engine_set_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'ma_bridge_engine_set_volume');
  late final _ma_bridge_engine_set_volume =
      _ma_bridge_engine_set_volumePtr.asFunction<void Function(double)>();

  /// Play a sound one-shot (fire and forget).
  /// @param path File path.
  void ma_bridge_engine_play_sound(
    ffi.Pointer<ffi.Char> path,
  ) {
    return _ma_bridge_engine_play_sound(
      path,
    );
  }

  late final _ma_bridge_engine_play_soundPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'ma_bridge_engine_play_sound');
  late final _ma_bridge_engine_play_sound = _ma_bridge_engine_play_soundPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Create/Load a sound.
  /// @return Sound Handle (pointer or ID). Returns 0/NULL on failure.
  ffi.Pointer<ffi.Void> ma_bridge_sound_init_from_file(
    ffi.Pointer<ffi.Char> path,
    int flags,
  ) {
    return _ma_bridge_sound_init_from_file(
      path,
      flags,
    );
  }

  late final _ma_bridge_sound_init_from_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Char>,
              ffi.Int32)>>('ma_bridge_sound_init_from_file');
  late final _ma_bridge_sound_init_from_file =
      _ma_bridge_sound_init_from_filePtr.asFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<ffi.Void> ma_bridge_sound_init_from_file_with_group(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Void> group_handle,
    int flags,
  ) {
    return _ma_bridge_sound_init_from_file_with_group(
      path,
      group_handle,
      flags,
    );
  }

  late final _ma_bridge_sound_init_from_file_with_groupPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Void>,
              ffi.Int32)>>('ma_bridge_sound_init_from_file_with_group');
  late final _ma_bridge_sound_init_from_file_with_group =
      _ma_bridge_sound_init_from_file_with_groupPtr.asFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Void>, int)>();

  void ma_bridge_sound_uninit(
    ffi.Pointer<ffi.Void> sound_handle,
  ) {
    return _ma_bridge_sound_uninit(
      sound_handle,
    );
  }

  late final _ma_bridge_sound_uninitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_sound_uninit');
  late final _ma_bridge_sound_uninit = _ma_bridge_sound_uninitPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void ma_bridge_sound_play(
    ffi.Pointer<ffi.Void> sound_handle,
  ) {
    return _ma_bridge_sound_play(
      sound_handle,
    );
  }

  late final _ma_bridge_sound_playPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_sound_play');
  late final _ma_bridge_sound_play = _ma_bridge_sound_playPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void ma_bridge_sound_stop(
    ffi.Pointer<ffi.Void> sound_handle,
  ) {
    return _ma_bridge_sound_stop(
      sound_handle,
    );
  }

  late final _ma_bridge_sound_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_sound_stop');
  late final _ma_bridge_sound_stop = _ma_bridge_sound_stopPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void ma_bridge_sound_set_volume(
    ffi.Pointer<ffi.Void> sound_handle,
    double volume,
  ) {
    return _ma_bridge_sound_set_volume(
      sound_handle,
      volume,
    );
  }

  late final _ma_bridge_sound_set_volumePtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_sound_set_volume');
  late final _ma_bridge_sound_set_volume = _ma_bridge_sound_set_volumePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  void ma_bridge_sound_set_pitch(
    ffi.Pointer<ffi.Void> sound_handle,
    double pitch,
  ) {
    return _ma_bridge_sound_set_pitch(
      sound_handle,
      pitch,
    );
  }

  late final _ma_bridge_sound_set_pitchPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_sound_set_pitch');
  late final _ma_bridge_sound_set_pitch = _ma_bridge_sound_set_pitchPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  void ma_bridge_sound_set_pan(
    ffi.Pointer<ffi.Void> sound_handle,
    double pan,
  ) {
    return _ma_bridge_sound_set_pan(
      sound_handle,
      pan,
    );
  }

  late final _ma_bridge_sound_set_panPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_sound_set_pan');
  late final _ma_bridge_sound_set_pan = _ma_bridge_sound_set_panPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  void ma_bridge_sound_set_looping(
    ffi.Pointer<ffi.Void> sound_handle,
    int loop,
  ) {
    return _ma_bridge_sound_set_looping(
      sound_handle,
      loop,
    );
  }

  late final _ma_bridge_sound_set_loopingPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)>>(
      'ma_bridge_sound_set_looping');
  late final _ma_bridge_sound_set_looping = _ma_bridge_sound_set_loopingPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();

  void ma_bridge_sound_set_position(
    ffi.Pointer<ffi.Void> sound_handle,
    double x,
    double y,
    double z,
  ) {
    return _ma_bridge_sound_set_position(
      sound_handle,
      x,
      y,
      z,
    );
  }

  late final _ma_bridge_sound_set_positionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float, ffi.Float,
              ffi.Float)>>('ma_bridge_sound_set_position');
  late final _ma_bridge_sound_set_position =
      _ma_bridge_sound_set_positionPtr.asFunction<
          void Function(ffi.Pointer<ffi.Void>, double, double, double)>();

  void ma_bridge_sound_set_direction(
    ffi.Pointer<ffi.Void> sound_handle,
    double x,
    double y,
    double z,
  ) {
    return _ma_bridge_sound_set_direction(
      sound_handle,
      x,
      y,
      z,
    );
  }

  late final _ma_bridge_sound_set_directionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float, ffi.Float,
              ffi.Float)>>('ma_bridge_sound_set_direction');
  late final _ma_bridge_sound_set_direction =
      _ma_bridge_sound_set_directionPtr.asFunction<
          void Function(ffi.Pointer<ffi.Void>, double, double, double)>();

  void ma_bridge_sound_set_velocity(
    ffi.Pointer<ffi.Void> sound_handle,
    double x,
    double y,
    double z,
  ) {
    return _ma_bridge_sound_set_velocity(
      sound_handle,
      x,
      y,
      z,
    );
  }

  late final _ma_bridge_sound_set_velocityPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float, ffi.Float,
              ffi.Float)>>('ma_bridge_sound_set_velocity');
  late final _ma_bridge_sound_set_velocity =
      _ma_bridge_sound_set_velocityPtr.asFunction<
          void Function(ffi.Pointer<ffi.Void>, double, double, double)>();

  void ma_bridge_sound_set_cone(
    ffi.Pointer<ffi.Void> sound_handle,
    double innerAngle,
    double outerAngle,
    double outerGain,
  ) {
    return _ma_bridge_sound_set_cone(
      sound_handle,
      innerAngle,
      outerAngle,
      outerGain,
    );
  }

  late final _ma_bridge_sound_set_conePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float, ffi.Float,
              ffi.Float)>>('ma_bridge_sound_set_cone');
  late final _ma_bridge_sound_set_cone =
      _ma_bridge_sound_set_conePtr.asFunction<
          void Function(ffi.Pointer<ffi.Void>, double, double, double)>();

  void ma_bridge_sound_set_doppler_factor(
    ffi.Pointer<ffi.Void> sound_handle,
    double factor,
  ) {
    return _ma_bridge_sound_set_doppler_factor(
      sound_handle,
      factor,
    );
  }

  late final _ma_bridge_sound_set_doppler_factorPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_sound_set_doppler_factor');
  late final _ma_bridge_sound_set_doppler_factor =
      _ma_bridge_sound_set_doppler_factorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  /// --- Listener API ---
  void ma_bridge_engine_listener_set_position(
    int listenerIndex,
    double x,
    double y,
    double z,
  ) {
    return _ma_bridge_engine_listener_set_position(
      listenerIndex,
      x,
      y,
      z,
    );
  }

  late final _ma_bridge_engine_listener_set_positionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int32, ffi.Float, ffi.Float,
              ffi.Float)>>('ma_bridge_engine_listener_set_position');
  late final _ma_bridge_engine_listener_set_position =
      _ma_bridge_engine_listener_set_positionPtr
          .asFunction<void Function(int, double, double, double)>();

  void ma_bridge_engine_listener_set_direction(
    int listenerIndex,
    double x,
    double y,
    double z,
  ) {
    return _ma_bridge_engine_listener_set_direction(
      listenerIndex,
      x,
      y,
      z,
    );
  }

  late final _ma_bridge_engine_listener_set_directionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int32, ffi.Float, ffi.Float,
              ffi.Float)>>('ma_bridge_engine_listener_set_direction');
  late final _ma_bridge_engine_listener_set_direction =
      _ma_bridge_engine_listener_set_directionPtr
          .asFunction<void Function(int, double, double, double)>();

  void ma_bridge_engine_listener_set_velocity(
    int listenerIndex,
    double x,
    double y,
    double z,
  ) {
    return _ma_bridge_engine_listener_set_velocity(
      listenerIndex,
      x,
      y,
      z,
    );
  }

  late final _ma_bridge_engine_listener_set_velocityPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int32, ffi.Float, ffi.Float,
              ffi.Float)>>('ma_bridge_engine_listener_set_velocity');
  late final _ma_bridge_engine_listener_set_velocity =
      _ma_bridge_engine_listener_set_velocityPtr
          .asFunction<void Function(int, double, double, double)>();

  void ma_bridge_engine_listener_set_world_up(
    int listenerIndex,
    double x,
    double y,
    double z,
  ) {
    return _ma_bridge_engine_listener_set_world_up(
      listenerIndex,
      x,
      y,
      z,
    );
  }

  late final _ma_bridge_engine_listener_set_world_upPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int32, ffi.Float, ffi.Float,
              ffi.Float)>>('ma_bridge_engine_listener_set_world_up');
  late final _ma_bridge_engine_listener_set_world_up =
      _ma_bridge_engine_listener_set_world_upPtr
          .asFunction<void Function(int, double, double, double)>();

  void ma_bridge_engine_listener_set_cone(
    int listenerIndex,
    double innerAngle,
    double outerAngle,
    double outerGain,
  ) {
    return _ma_bridge_engine_listener_set_cone(
      listenerIndex,
      innerAngle,
      outerAngle,
      outerGain,
    );
  }

  late final _ma_bridge_engine_listener_set_conePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int32, ffi.Float, ffi.Float,
              ffi.Float)>>('ma_bridge_engine_listener_set_cone');
  late final _ma_bridge_engine_listener_set_cone =
      _ma_bridge_engine_listener_set_conePtr
          .asFunction<void Function(int, double, double, double)>();

  void ma_bridge_engine_listener_set_enabled(
    int listenerIndex,
    int enabled,
  ) {
    return _ma_bridge_engine_listener_set_enabled(
      listenerIndex,
      enabled,
    );
  }

  late final _ma_bridge_engine_listener_set_enabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int32, ffi.Int32)>>(
          'ma_bridge_engine_listener_set_enabled');
  late final _ma_bridge_engine_listener_set_enabled =
      _ma_bridge_engine_listener_set_enabledPtr
          .asFunction<void Function(int, int)>();

  void ma_bridge_sound_set_fade_in_pcm_frames(
    ffi.Pointer<ffi.Void> sound_handle,
    double volumeBeg,
    double volumeEnd,
    int len,
  ) {
    return _ma_bridge_sound_set_fade_in_pcm_frames(
      sound_handle,
      volumeBeg,
      volumeEnd,
      len,
    );
  }

  late final _ma_bridge_sound_set_fade_in_pcm_framesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float, ffi.Float,
              ffi.Uint64)>>('ma_bridge_sound_set_fade_in_pcm_frames');
  late final _ma_bridge_sound_set_fade_in_pcm_frames =
      _ma_bridge_sound_set_fade_in_pcm_framesPtr.asFunction<
          void Function(ffi.Pointer<ffi.Void>, double, double, int)>();

  void ma_bridge_sound_set_fade_start_time(
    ffi.Pointer<ffi.Void> sound_handle,
    double volumeBeg,
    double volumeEnd,
    int len,
    int absoluteGlobalTime,
  ) {
    return _ma_bridge_sound_set_fade_start_time(
      sound_handle,
      volumeBeg,
      volumeEnd,
      len,
      absoluteGlobalTime,
    );
  }

  late final _ma_bridge_sound_set_fade_start_timePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float, ffi.Float,
              ffi.Uint64, ffi.Uint64)>>('ma_bridge_sound_set_fade_start_time');
  late final _ma_bridge_sound_set_fade_start_time =
      _ma_bridge_sound_set_fade_start_timePtr.asFunction<
          void Function(ffi.Pointer<ffi.Void>, double, double, int, int)>();

  void ma_bridge_sound_seek_to_pcm_frame(
    ffi.Pointer<ffi.Void> sound_handle,
    int frameIndex,
  ) {
    return _ma_bridge_sound_seek_to_pcm_frame(
      sound_handle,
      frameIndex,
    );
  }

  late final _ma_bridge_sound_seek_to_pcm_framePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>,
              ffi.Uint64)>>('ma_bridge_sound_seek_to_pcm_frame');
  late final _ma_bridge_sound_seek_to_pcm_frame =
      _ma_bridge_sound_seek_to_pcm_framePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();

  int ma_bridge_sound_get_length_in_pcm_frames(
    ffi.Pointer<ffi.Void> sound_handle,
  ) {
    return _ma_bridge_sound_get_length_in_pcm_frames(
      sound_handle,
    );
  }

  late final _ma_bridge_sound_get_length_in_pcm_framesPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_sound_get_length_in_pcm_frames');
  late final _ma_bridge_sound_get_length_in_pcm_frames =
      _ma_bridge_sound_get_length_in_pcm_framesPtr
          .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  int ma_bridge_sound_get_cursor_in_pcm_frames(
    ffi.Pointer<ffi.Void> sound_handle,
  ) {
    return _ma_bridge_sound_get_cursor_in_pcm_frames(
      sound_handle,
    );
  }

  late final _ma_bridge_sound_get_cursor_in_pcm_framesPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_sound_get_cursor_in_pcm_frames');
  late final _ma_bridge_sound_get_cursor_in_pcm_frames =
      _ma_bridge_sound_get_cursor_in_pcm_framesPtr
          .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  int ma_bridge_sound_is_playing(
    ffi.Pointer<ffi.Void> sound_handle,
  ) {
    return _ma_bridge_sound_is_playing(
      sound_handle,
    );
  }

  late final _ma_bridge_sound_is_playingPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_sound_is_playing');
  late final _ma_bridge_sound_is_playing = _ma_bridge_sound_is_playingPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  int ma_bridge_sound_at_end(
    ffi.Pointer<ffi.Void> sound_handle,
  ) {
    return _ma_bridge_sound_at_end(
      sound_handle,
    );
  }

  late final _ma_bridge_sound_at_endPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_sound_at_end');
  late final _ma_bridge_sound_at_end = _ma_bridge_sound_at_endPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  /// --- Sound Group API ---
  ffi.Pointer<ffi.Void> ma_bridge_sound_group_init(
    ffi.Pointer<ffi.Void> parent_group_handle,
  ) {
    return _ma_bridge_sound_group_init(
      parent_group_handle,
    );
  }

  late final _ma_bridge_sound_group_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>)>>('ma_bridge_sound_group_init');
  late final _ma_bridge_sound_group_init = _ma_bridge_sound_group_initPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();

  void ma_bridge_sound_group_uninit(
    ffi.Pointer<ffi.Void> group_handle,
  ) {
    return _ma_bridge_sound_group_uninit(
      group_handle,
    );
  }

  late final _ma_bridge_sound_group_uninitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_sound_group_uninit');
  late final _ma_bridge_sound_group_uninit = _ma_bridge_sound_group_uninitPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void ma_bridge_sound_group_start(
    ffi.Pointer<ffi.Void> group_handle,
  ) {
    return _ma_bridge_sound_group_start(
      group_handle,
    );
  }

  late final _ma_bridge_sound_group_startPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_sound_group_start');
  late final _ma_bridge_sound_group_start = _ma_bridge_sound_group_startPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void ma_bridge_sound_group_stop(
    ffi.Pointer<ffi.Void> group_handle,
  ) {
    return _ma_bridge_sound_group_stop(
      group_handle,
    );
  }

  late final _ma_bridge_sound_group_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_sound_group_stop');
  late final _ma_bridge_sound_group_stop = _ma_bridge_sound_group_stopPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void ma_bridge_sound_group_set_volume(
    ffi.Pointer<ffi.Void> group_handle,
    double volume,
  ) {
    return _ma_bridge_sound_group_set_volume(
      group_handle,
      volume,
    );
  }

  late final _ma_bridge_sound_group_set_volumePtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_sound_group_set_volume');
  late final _ma_bridge_sound_group_set_volume =
      _ma_bridge_sound_group_set_volumePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  void ma_bridge_sound_group_set_pan(
    ffi.Pointer<ffi.Void> group_handle,
    double pan,
  ) {
    return _ma_bridge_sound_group_set_pan(
      group_handle,
      pan,
    );
  }

  late final _ma_bridge_sound_group_set_panPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_sound_group_set_pan');
  late final _ma_bridge_sound_group_set_pan = _ma_bridge_sound_group_set_panPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  void ma_bridge_sound_group_set_pitch(
    ffi.Pointer<ffi.Void> group_handle,
    double pitch,
  ) {
    return _ma_bridge_sound_group_set_pitch(
      group_handle,
      pitch,
    );
  }

  late final _ma_bridge_sound_group_set_pitchPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_sound_group_set_pitch');
  late final _ma_bridge_sound_group_set_pitch =
      _ma_bridge_sound_group_set_pitchPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  /// Load sound from memory buffer.
  /// @param data Pointer to audio data (MP3/WAV/etc).
  /// @param size Size of buffer in bytes.
  /// @return Sound Handle.
  ffi.Pointer<ffi.Void> ma_bridge_sound_init_from_memory(
    ffi.Pointer<ffi.Void> data,
    int size,
    int flags,
  ) {
    return _ma_bridge_sound_init_from_memory(
      data,
      size,
      flags,
    );
  }

  late final _ma_bridge_sound_init_from_memoryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size,
              ffi.Int32)>>('ma_bridge_sound_init_from_memory');
  late final _ma_bridge_sound_init_from_memory =
      _ma_bridge_sound_init_from_memoryPtr.asFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int, int)>();

  /// Create a noise sound.
  /// @param type 0=White, 1=Pink, 2=Brownian.
  /// @param amplitude 0.0 to 1.0.
  /// @param seed Random seed.
  /// @return Sound Handle.
  ffi.Pointer<ffi.Void> ma_bridge_sound_init_noise(
    int type,
    double amplitude,
    int seed,
  ) {
    return _ma_bridge_sound_init_noise(
      type,
      amplitude,
      seed,
    );
  }

  late final _ma_bridge_sound_init_noisePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Int32, ffi.Float, ffi.Int32)>>('ma_bridge_sound_init_noise');
  late final _ma_bridge_sound_init_noise = _ma_bridge_sound_init_noisePtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int, double, int)>();

  /// Create a waveform sound.
  /// @param type 0=Sine, 1=Square, 2=Triangle, 3=Sawtooth.
  /// @param amplitude 0.0 to 1.0.
  /// @param frequency Hz.
  /// @return Sound Handle.
  ffi.Pointer<ffi.Void> ma_bridge_sound_init_waveform(
    int type,
    double amplitude,
    double frequency,
  ) {
    return _ma_bridge_sound_init_waveform(
      type,
      amplitude,
      frequency,
    );
  }

  late final _ma_bridge_sound_init_waveformPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Int32, ffi.Float,
              ffi.Double)>>('ma_bridge_sound_init_waveform');
  late final _ma_bridge_sound_init_waveform = _ma_bridge_sound_init_waveformPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int, double, double)>();

  /// Delay Node
  ffi.Pointer<ffi.Void> ma_bridge_node_delay_init() {
    return _ma_bridge_node_delay_init();
  }

  late final _ma_bridge_node_delay_initPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
          'ma_bridge_node_delay_init');
  late final _ma_bridge_node_delay_init = _ma_bridge_node_delay_initPtr
      .asFunction<ffi.Pointer<ffi.Void> Function()>();

  void ma_bridge_node_delay_set_delay(
    ffi.Pointer<ffi.Void> node_handle,
    double delayInSeconds,
  ) {
    return _ma_bridge_node_delay_set_delay(
      node_handle,
      delayInSeconds,
    );
  }

  late final _ma_bridge_node_delay_set_delayPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_node_delay_set_delay');
  late final _ma_bridge_node_delay_set_delay =
      _ma_bridge_node_delay_set_delayPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  void ma_bridge_node_delay_set_wet(
    ffi.Pointer<ffi.Void> node_handle,
    double wet,
  ) {
    return _ma_bridge_node_delay_set_wet(
      node_handle,
      wet,
    );
  }

  late final _ma_bridge_node_delay_set_wetPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_node_delay_set_wet');
  late final _ma_bridge_node_delay_set_wet = _ma_bridge_node_delay_set_wetPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  void ma_bridge_node_delay_set_dry(
    ffi.Pointer<ffi.Void> node_handle,
    double dry,
  ) {
    return _ma_bridge_node_delay_set_dry(
      node_handle,
      dry,
    );
  }

  late final _ma_bridge_node_delay_set_dryPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_node_delay_set_dry');
  late final _ma_bridge_node_delay_set_dry = _ma_bridge_node_delay_set_dryPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  void ma_bridge_node_delay_set_decay(
    ffi.Pointer<ffi.Void> node_handle,
    double decay,
  ) {
    return _ma_bridge_node_delay_set_decay(
      node_handle,
      decay,
    );
  }

  late final _ma_bridge_node_delay_set_decayPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_node_delay_set_decay');
  late final _ma_bridge_node_delay_set_decay =
      _ma_bridge_node_delay_set_decayPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  /// Reverb Node
  ffi.Pointer<ffi.Void> ma_bridge_node_reverb_init() {
    return _ma_bridge_node_reverb_init();
  }

  late final _ma_bridge_node_reverb_initPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
          'ma_bridge_node_reverb_init');
  late final _ma_bridge_node_reverb_init = _ma_bridge_node_reverb_initPtr
      .asFunction<ffi.Pointer<ffi.Void> Function()>();

  void ma_bridge_node_reverb_set_params(
    ffi.Pointer<ffi.Void> node_handle,
    double roomSize,
    double damping,
    double width,
    double wet,
    double dry,
  ) {
    return _ma_bridge_node_reverb_set_params(
      node_handle,
      roomSize,
      damping,
      width,
      wet,
      dry,
    );
  }

  late final _ma_bridge_node_reverb_set_paramsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float)>>('ma_bridge_node_reverb_set_params');
  late final _ma_bridge_node_reverb_set_params =
      _ma_bridge_node_reverb_set_paramsPtr.asFunction<
          void Function(
              ffi.Pointer<ffi.Void>, double, double, double, double, double)>();

  /// LPF (Low Pass Filter) Node
  ffi.Pointer<ffi.Void> ma_bridge_node_lpf_init() {
    return _ma_bridge_node_lpf_init();
  }

  late final _ma_bridge_node_lpf_initPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
          'ma_bridge_node_lpf_init');
  late final _ma_bridge_node_lpf_init = _ma_bridge_node_lpf_initPtr
      .asFunction<ffi.Pointer<ffi.Void> Function()>();

  void ma_bridge_node_lpf_set_cutoff(
    ffi.Pointer<ffi.Void> node_handle,
    double cutoffFrequency,
  ) {
    return _ma_bridge_node_lpf_set_cutoff(
      node_handle,
      cutoffFrequency,
    );
  }

  late final _ma_bridge_node_lpf_set_cutoffPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_node_lpf_set_cutoff');
  late final _ma_bridge_node_lpf_set_cutoff = _ma_bridge_node_lpf_set_cutoffPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  /// HPF (High Pass Filter) Node
  ffi.Pointer<ffi.Void> ma_bridge_node_hpf_init() {
    return _ma_bridge_node_hpf_init();
  }

  late final _ma_bridge_node_hpf_initPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
          'ma_bridge_node_hpf_init');
  late final _ma_bridge_node_hpf_init = _ma_bridge_node_hpf_initPtr
      .asFunction<ffi.Pointer<ffi.Void> Function()>();

  void ma_bridge_node_hpf_set_cutoff(
    ffi.Pointer<ffi.Void> node_handle,
    double cutoffFrequency,
  ) {
    return _ma_bridge_node_hpf_set_cutoff(
      node_handle,
      cutoffFrequency,
    );
  }

  late final _ma_bridge_node_hpf_set_cutoffPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Float)>>(
      'ma_bridge_node_hpf_set_cutoff');
  late final _ma_bridge_node_hpf_set_cutoff = _ma_bridge_node_hpf_set_cutoffPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, double)>();

  /// Node Management
  void ma_bridge_node_uninit(
    ffi.Pointer<ffi.Void> node_handle,
  ) {
    return _ma_bridge_node_uninit(
      node_handle,
    );
  }

  late final _ma_bridge_node_uninitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'ma_bridge_node_uninit');
  late final _ma_bridge_node_uninit = _ma_bridge_node_uninitPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// Routing
  /// /**
  ///  * Route a Sound to a specific Node (instead of the Engine's master output).
  ///  * @param sound_handle The sound to reroute.
  ///  * @param node_handle The effect node to connect to. If NULL, connects to Engine Output.
  ///  */
  void ma_bridge_sound_route_to_node(
    ffi.Pointer<ffi.Void> sound_handle,
    ffi.Pointer<ffi.Void> node_handle,
  ) {
    return _ma_bridge_sound_route_to_node(
      sound_handle,
      node_handle,
    );
  }

  late final _ma_bridge_sound_route_to_nodePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>)>>('ma_bridge_sound_route_to_node');
  late final _ma_bridge_sound_route_to_node =
      _ma_bridge_sound_route_to_nodePtr.asFunction<
          void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>();

  /// Chain nodes: Node A output -> Node B input.
  /// @param source_node The upstream node.
  /// @param dest_node The downstream node. If NULL, connects to Engine Output.
  void ma_bridge_node_attach_output_bus(
    ffi.Pointer<ffi.Void> source_node,
    int source_bus,
    ffi.Pointer<ffi.Void> dest_node,
    int dest_bus,
  ) {
    return _ma_bridge_node_attach_output_bus(
      source_node,
      source_bus,
      dest_node,
      dest_bus,
    );
  }

  late final _ma_bridge_node_attach_output_busPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Int32,
              ffi.Pointer<ffi.Void>,
              ffi.Int32)>>('ma_bridge_node_attach_output_bus');
  late final _ma_bridge_node_attach_output_bus =
      _ma_bridge_node_attach_output_busPtr.asFunction<
          void Function(
              ffi.Pointer<ffi.Void>, int, ffi.Pointer<ffi.Void>, int)>();

  void ma_bridge_deinit() {
    return _ma_bridge_deinit();
  }

  late final _ma_bridge_deinitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('ma_bridge_deinit');
  late final _ma_bridge_deinit =
      _ma_bridge_deinitPtr.asFunction<void Function()>();
}
